### ISSUE TITLE
Missing call to `apt-get upgrade`?

### ISSUE THREAD

**Issue by adamnfish** [guardian/parking-lot#1]
I've had a look through the packer scripts and it doesn't look like there's any call to `apt-get upgrade`. This means it'll be creating AMIs with out-of-date software. Perhaps I'm misreading it (or perhaps there is such a call at instance start time?)

I'd imagine it should be roughly here:
https://github.com/guardian/parking-lot/blob/master/scripts/setup.sh#L14

If anyone knows how this project works and would like to shed light, that'd be great.

**Comment by sihil** [comment]
This project is being EOLed with the domains project that @jennysivapalan is working on. As such we should not worry and look to shut it down as soon as practical.

**Comment by jennysivapalan** [comment]
I'm on it! :car:

**Comment by adamnfish** [comment]
:ok_hand:
